### PR TITLE
Ensure a DC eligibility option is chosen

### PR DESCRIPTION
**Pull request by benlovell**
There was no validation being performed on this form value prior to
this change.

screen shot 2017-02-08 at 15 04 45

screen shot 2017-02-08 at 15 04 52

### CODE REVIEW

**Comment by Guntrisoft** [comment]
`can't be blank` seems like odd terminology to me

**Comment by benlovell** [comment]
@Guntrisoft That's standard Rails terminology, used everywhere else when a value is not provided. Do you have a better suggestion?

**Comment by Guntrisoft** [comment]
Agreed with content team this is ok.

**Comment by Guntrisoft** [comment]
👍

**Pull request merged**
