### PR TITLE
Stop /home-alternative from being indexed by search engines

### PR DESCRIPTION
**Pull request by Guntrisoft**

### CODE REVIEW

**Comment by Guntrisoft** [comment]
@benbarnett

**Comment by benlovell** [comment]
Perhaps we should just specify the canonical URL - inclusive of the scheme (HTTPS) - globally?

**Comment by benbarnett** [comment]
Agree with @benlovell. Perhaps the `content_for` is to provide the path only, and the FQDN is just part of the template.

**Comment by benlovell** [comment]
@Guntrisoft there's an initializer in `config/initializers/canonical_rails.rb` where you can configure this globally - in that case.

**Comment by Guntrisoft** [comment]
@benlovell @benbarnett re-jigged the commit, thoughts?

**Comment by benbarnett** [comment]
image

**Pull request merged**
