### PR TITLE
New guide on combining pension pots

### PR DESCRIPTION
**Pull request by alexkouz**

### CODE REVIEW

**Comment by andrewgarner** [comment]
What is happening to https://www.pensionwise.gov.uk/pension-pot-value#combine-your-pension-pots ?

**Comment by alexkouz** [comment]
Will be adding a link – can do so once published or in this 'channel'...

**Comment by andrewgarner** [comment]
We should update it here then release it as one.

**Comment by NikkiAlbon** [comment]
'tree'

**Comment by alexkouz** [comment]
Changes made, can see them here: https://github.com/guidance-guarantee-programme/pension_guidance/commit/87d3f840eb0a59a0917f1c97d28d99516833e303

**Pull request merged**
