### PR TITLE
Reword provider content

### PR DESCRIPTION
**Pull request by benlovell**
Rewords provider content inline with recommendations.

### CODE REVIEW

**Comment by benlovell** [comment]
@arwelowen Could you please translate these alterations?

**Comment by benlovell** [comment]
@arwelowen Any joy with `providers.cy.md`? Give me a shout if you need help.

**Comment by arwelowen** [comment]
Hi Ben

I put a note in GIT yesterday saying I was having issues with the ‘fork’.

When I looked at the file I noted that the changes have been done for the Welsh and these were correct and was good to go. For some reason it wouldn’t allow me to push.

Regards

Arwel

Arwel Owen
Welsh Language Unit | Department for Work and Pensions | Work Services Directorate | Wales Group| Out stationed at Pwllheli JCP | Lower Cardiff Road | Pwllheli | Gwynedd | LL53 5BY | Tel. 01758 632601| www.dwp.gov.uk<http://www.dwp.gov.uk/>
Uned yr Iaith Gymraeg | Adran Gwaith a Phensiynau | Cyfarwyddiaeth Gwasanaethau Gwaith | Grŵp  Cymru | Yn Gweithio allan o CBG Pwllheli | Lower Cardiff Road | Pwllheli | Gwynedd | LL53 5BY | Ffôn 01758 632 601 | www.dwp.gov.uk/cymraeg<http://www.dwp.gov.uk/cymraeg>
Please consider the environment before printing/Ystyriwch yr amgylchedd cyn argraffu

**Comment by benlovell** [comment]
@arwelowen Ah, I don't think I made it particularly clear but I renamed what was `designated_providers.cy.md` to `providers.cy.md` and made some alterations to the English version that need to be translated. Basically `providers.en.md` and `providers.cy.md` need to match. Give me a shout if this doesn't make sense!

**Comment by arwelowen** [comment]
@benlovell I've now got to the right file but when I try and edit it I get the message 'Waiting for your fork…' and the green button to propose a change is shaded out. I've copied what the Welsh should be below, could you drop it into the providers.cy.md for me?

---
label: Darparwyr arweiniad Pension Wise
description: Darparwyr arweiniad Pension Wise
---

# Darparwyr arweiniad Pension Wise

Y darparwyr arweiniad Pension Wise yw:

* Corff Cyfarwyddyd Ariannol Sengl
* Y Gwasanaeth Cynghori ar Bensiynau Cyfyngedig
* Cymdeithas Genedlaethol Cyngor ar Bopeth
* Cymdeithas Cyngor ar Bopeth yr Alban
* Teleperformance SE

**Comment by benlovell** [comment]
@arwelowen Brill, cheers 👍

**Pull request merged**
