### PR TITLE
Homepage rebrand

### PR DESCRIPTION
**Pull request by benbarnett**
Brings in-line with new marketing campaign.

### CODE REVIEW

**Comment by Guntrisoft** [comment]
screen shot 2016-10-20 at 11 54 26

**Comment by Guntrisoft** [comment]
@benbarnett the dark colour of the gradient passes large text AA

**Comment by benbarnett** [comment]
@Guntrisoft have changed to colours that pass AA checks now

**Comment by Guntrisoft** [comment]
👍

**Comment by benlovell** [comment]
Nice. 👌💯

**Pull request merged**
