### PR TITLE
Fix intermittently failing tests by disabling jQuery animations in test environment

### PR DESCRIPTION
**Pull request by Guntrisoft**
In order to fix the following error: -

``And I provide my personal details                # features/step_definitions/customer_booking_request_steps.rb:62
      expected `#<Pages::BookingStepTwo:0x007ff751ff1770 @addressable_url_matcher=#<SitePrism::AddressableUrlMatcher:0x007ff751ff07d0 @pattern="/locations/{id}/booking-request/step-two", @substitutions={"{id}"=>"tlifxq"}, @reverse_substitutions={"tlifxq"=>"{id}"}, @component_templates={:path=>#<Addressable::Template:0x3ffba8ff1958 PATTERN:/locations/{id}/booking-request/step-two>}>>.displayed?` to return true, got false (RSpec::Expectations::ExpectationNotMetError)
      ./features/support/booking_requests.rb:5:in `block in <top (required)>'
      ./features/support/booking_locations.rb:7:in `block in <top (required)>'
      features/customer_booking_request.feature:24:in `And I provide my personal details'
``

which often crops up when running the build.

### CODE REVIEW

**Comment by Guntrisoft** [comment]
@benbarnett

**Comment by dwhenry** [comment]
For reference seems like it is related to this: https://github.com/teampoltergeist/poltergeist/issues/530#issuecomment-129264353

**Comment by benbarnett** [comment]
@Guntrisoft @dwhenry happy with this?

**Comment by dwhenry** [comment]
Looks good to me.

**Comment by Guntrisoft** [comment]
@benbarnett yup - you can be @benlovell hero instead 👍

**Comment by benlovell** [comment]
I cannot put into words how utterly satisfying this experience has been.

**Pull request merged**
